"""Data loading for the Simpsons-MNIST model-collapse experiments.

Two data sources are supported so that later "generations" of the VAE can be
trained on *synthetic* images produced by an earlier generation:

  * ``folder`` -- the real Simpsons-MNIST grayscale images on disk
    (``dataset/simpsons-mnist/grayscale/{train,test}/<class>/*.jpg``).
  * ``npz``    -- a ``synthetic_data.npz`` file written by ``vae.py`` for a
    previous generation. It contains an ``images`` array of shape
    ``(N, 28, 28)`` with ``uint8`` values in ``[0, 255]``.

Both sources yield tensors of shape ``(1, 28, 28)`` scaled to ``[0, 1]`` so the
rest of the pipeline is agnostic to where the data came from.
"""

from __future__ import annotations

import glob
import os

import numpy as np
import torch
from PIL import Image
from torch.utils.data import DataLoader, Dataset

IMAGE_SIZE = 28
REAL_ROOT = os.path.join("dataset", "simpsons-mnist", "grayscale")

# Fixed class ordering so the FID feature-extractor labels are stable across runs.
CLASSES = [
    "bart_simpson",
    "charles_montgomery_burns",
    "homer_simpson",
    "krusty_the_clown",
    "lisa_simpson",
    "marge_simpson",
    "milhouse_van_houten",
    "moe_szyslak",
    "ned_flanders",
    "principal_skinner",
]
CLASS_TO_IDX = {name: i for i, name in enumerate(CLASSES)}


class FolderDataset(Dataset):
    """Reads the real grayscale Simpsons-MNIST images from a split folder."""

    def __init__(self, split: str = "train", root: str = REAL_ROOT):
        self.paths: list[str] = []
        self.labels: list[int] = []
        for cls in CLASSES:
            for path in sorted(glob.glob(os.path.join(root, split, cls, "*.jpg"))):
                self.paths.append(path)
                self.labels.append(CLASS_TO_IDX[cls])
        if not self.paths:
            raise FileNotFoundError(
                f"No images found under {os.path.join(root, split)!r}."
            )

    def __len__(self) -> int:
        return len(self.paths)

    def __getitem__(self, idx: int):
        img = Image.open(self.paths[idx]).convert("L")
        arr = np.asarray(img, dtype=np.float32) / 255.0
        tensor = torch.from_numpy(arr).unsqueeze(0)  # (1, 28, 28)
        return tensor, self.labels[idx]


class NpzDataset(Dataset):
    """Reads synthetic images generated by a previous VAE generation.

    Labels are unavailable for unconditional samples, so a dummy label of -1 is
    returned. Only the images matter for training the next-generation VAE.
    """

    def __init__(self, npz_path: str):
        data = np.load(npz_path)
        images = data["images"]  # (N, 28, 28) uint8
        if images.ndim != 3 or images.shape[1:] != (IMAGE_SIZE, IMAGE_SIZE):
            raise ValueError(
                f"Expected images of shape (N, 28, 28), got {images.shape}."
            )
        self.images = images.astype(np.float32) / 255.0
        self.labels = data["labels"] if "labels" in data else np.full(len(images), -1)

    def __len__(self) -> int:
        return len(self.images)

    def __getitem__(self, idx: int):
        tensor = torch.from_numpy(self.images[idx]).unsqueeze(0)  # (1, 28, 28)
        return tensor, int(self.labels[idx])


def build_dataset(source: str, split: str = "train") -> Dataset:
    """Factory: ``source`` is either ``"folder"`` or a path to an ``.npz`` file."""
    if source == "folder":
        return FolderDataset(split=split)
    if source.endswith(".npz"):
        return NpzDataset(source)
    raise ValueError(
        f"Unknown data source {source!r}. Use 'folder' or a path to an .npz file."
    )


def build_loader(
    source: str,
    split: str = "train",
    batch_size: int = 128,
    shuffle: bool = True,
    num_workers: int = 0,
) -> DataLoader:
    dataset = build_dataset(source, split=split)
    return DataLoader(
        dataset,
        batch_size=batch_size,
        shuffle=shuffle,
        num_workers=num_workers,
        drop_last=False,
        pin_memory=torch.cuda.is_available(),
    )
